name = "attestofrontend"
compatibility_date = "2025-10-07"
# account_id = "YOUR_ACCOUNT_ID"          # optional but recommended in CI

[assets]
directory = "dist"                         # produced by `astro build`
html_handling = "auto-trailing-slash"      # <-- was "auto"; use one of the allowed values
